# Generated by Django 4.0.5 on 2022-06-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='dt_created',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='content',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='feeling',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='score',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='nation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
